# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run cube script

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.10
              uses: actions/setup-python@v2
              with:
                  python-version: '3.10'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install beautifulsoup4
                  pip install lxml
            - name: Run the cube script
              run: |
                  workingdir=`pwd`
                  xmlfile=$workingdir'/pkto_cockatrice.xml'
                  python3 $workingdir'/scripts/cube_compiler_script.py' -f $xmlfile
                  - uses: actions/upload-artifact@v3
            - name: Write cube artifact
            - uses: actions/upload-artifact@v3
              with:
                  name: cube file
                  path: pkto_cube.txt
